version: '3.6'

services:
  OneNode:
    build:
      context: .
      dockerfile: docker/Dockerfile.onenode
      args:
        - HTTP_PROXY=${http_proxy}
        - HTTPS_PROXY=${https_proxy}
        - no_proxy=${no_proxy}
    image: onenode
    container_name: onenode
    init: true
    environment:
      LANG: "zh_CN.UTF-8"
      LC_ALL: "zh_CN.UTF-8"
      TMPDIR: "/tmp"
      PORT: "8120"
      HF_URL: "${HF_URL}"
      HOST_URL: "${HOST_URL}"
      OMPT_URL: "${OMPT_URL}"
      INTERVL_URL: "${INTERVL_URL}"
      LLM_SRV1_URL: "${LLM_SRV1_URL}"
      LLM_SRV2_URL: "${LLM_SRV2_URL}"
      MEM_GRAPH_URL: "${MEM_GRAPH_URL}"
      PYTHONPATH: "/OneNode"
    volumes:
      - ./is_kb:/is_kb
      - ./backend:/OneNode
      - ./build:/build
    ports:
      - "8120:8120"
    restart: unless-stopped
    networks:
      - onenode_network

  memgraph:
    image: memgraph/memgraph:latest
    container_name: memgraph
    ports:
      - "7687:7687"
    restart: unless-stopped
    networks:
      - onenode_network


networks:
  onenode_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
